export enum MessageValidationError {
  INVALID_SIGNATURE = 'INVALID_SIGNATURE',
  TOO_DOLD = 'TOO_OLD',
  TOO_FUTURE = 'TOO_FUTURE',
  MISSING_MESSAGE_ID = 'MISSING_MESSAGE_ID',
  DUPLICATE_MESSAGE = 'DUPLICATE_MESSAGE',
  PROCESSED_ERROR = 'PROCESSED_ERROR',
}
